version: "3.8"

services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entryPoints.web.address=:9000"
    ports:
      - "8080:8080"     
      - "9000:9000"  
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik
    # labels:
    # - "traefik.http.middlewares.auth-basic.basicauth.users=admin:$2y$05$dVJqEWPx7WVjdAVjTuBdQOecAyhjT1h8yCOaub7jtRZmUhs9Fct8O"

networks:
  traefik:
    driver: bridge
